/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JList;

/**
 *
 * @author rahma
 */
public class GUI_Register extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Register
     */
    public GUI_Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfPass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbGender = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        tfNohp = new javax.swing.JTextField();
        btnRegisterDonatur = new javax.swing.JButton();
        btnBacktologin = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tfAlamat = new javax.swing.JTextField();
        Tempat = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListNama = new javax.swing.JList<>();
        RegisterPenggalangdanaBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taInfo = new javax.swing.JTextArea();
        btnViewDonatur = new javax.swing.JButton();
        btnViewPenggalangdana = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListPenggalang = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        Penggalangdana = new javax.swing.JTextArea();
        jDateLahir = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(80, 148, 101));
        jLabel1.setText("REGISTER AKUN");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        jLabel2.setText("NAMA ");

        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        jLabel3.setText("EMAIL");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        jLabel4.setText("USERNAME");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        jLabel5.setText("PASSWORD");

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        jLabel6.setText("Tempat TANGGAL LAHIR");

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        jLabel7.setText("GENDER");

        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki- Laki", "Perempuan" }));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        jLabel8.setText("NO HP");

        tfNohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNohpActionPerformed(evt);
            }
        });
        tfNohp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNohpKeyTyped(evt);
            }
        });

        btnRegisterDonatur.setBackground(new java.awt.Color(248, 248, 248));
        btnRegisterDonatur.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        btnRegisterDonatur.setForeground(new java.awt.Color(80, 148, 101));
        btnRegisterDonatur.setText("REGISTER as Donatur");
        btnRegisterDonatur.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(248, 248, 248), 2, true));
        btnRegisterDonatur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterDonaturActionPerformed(evt);
            }
        });

        btnBacktologin.setBackground(new java.awt.Color(248, 248, 248));
        btnBacktologin.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        btnBacktologin.setForeground(new java.awt.Color(80, 148, 101));
        btnBacktologin.setText("Login");
        btnBacktologin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnBacktologin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBacktologinActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        jLabel9.setText("ALAMAT");

        jScrollPane2.setViewportView(ListNama);

        RegisterPenggalangdanaBtn.setBackground(new java.awt.Color(204, 204, 204));
        RegisterPenggalangdanaBtn.setText("Register as Admin");
        RegisterPenggalangdanaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterPenggalangdanaBtnActionPerformed(evt);
            }
        });

        taInfo.setColumns(20);
        taInfo.setRows(5);
        jScrollPane1.setViewportView(taInfo);

        btnViewDonatur.setText("View Donatur");
        btnViewDonatur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDonaturActionPerformed(evt);
            }
        });

        btnViewPenggalangdana.setText("View Penggalang Dana");

        jScrollPane3.setViewportView(ListPenggalang);

        Penggalangdana.setColumns(20);
        Penggalangdana.setRows(5);
        jScrollPane4.setViewportView(Penggalangdana);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel5))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfAlamat, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfPass)
                                    .addComponent(tfEmail)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(tfNama))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7))
                                        .addGap(93, 93, 93)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfNohp, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnRegisterDonatur, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RegisterPenggalangdanaBtn)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addGap(16, 16, 16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Tempat, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDateLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnViewDonatur)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnViewPenggalangdana)
                                .addGap(34, 34, 34)
                                .addComponent(btnBacktologin, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(Tempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(tfNohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RegisterPenggalangdanaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegisterDonatur, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBacktologin)
                    .addComponent(btnViewDonatur)
                    .addComponent(btnViewPenggalangdana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaActionPerformed

    private void tfNohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNohpActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfNohpActionPerformed

    private void tfNohpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNohpKeyTyped
        // TODO add your handling code here:

        // TODO add your handling code here:
        char cDigit = evt.getKeyChar();
        if (!Character.isDigit(cDigit)) {
            evt.consume();

        }

    }//GEN-LAST:event_tfNohpKeyTyped

    private void btnRegisterDonaturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterDonaturActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterDonaturActionPerformed

    private void btnBacktologinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBacktologinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBacktologinActionPerformed

    private void RegisterPenggalangdanaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterPenggalangdanaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterPenggalangdanaBtnActionPerformed

    private void btnViewDonaturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDonaturActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewDonaturActionPerformed

    /**
     * @param args the command line arguments
     */
    public String getUsername() {
        return tfUsername.getText();
    }

    public String getEmail() {
        return tfEmail.getText();
    }

    public String getNama() {
        return tfNama.getText();
    }

    public String getPass() {
        return tfPass.getText();
    }

    public String getGender() {
        int i = cbGender.getSelectedIndex();
        return cbGender.getItemAt(i);
    }

    public String getNo_HP() {
        return tfNohp.getText();
    }

    public String getAlamat() {
        return tfAlamat.getText();
    }

    public String getTempatLahir() {
        return Tempat.getText();
    }
public void setListNama(String[] isi) {
        ListNama.setListData(isi);
    }

    public void setListPenggalang(String[] isi) {
        ListPenggalang.setListData(isi);
    }

    public void resetView() {
        tfUsername.setText("");
        tfPass.setText("");
        cbGender.setSelectedIndex(0);
        tfEmail.setText("");
        tfNohp.setText("");
        tfAlamat.setText("");
        tfNama.setText("");
    }

    public int getIndex() {
        return ListNama.getSelectedIndex();
    }
    public int getIndexpenggalang(){
        return ListPenggalang.getSelectedIndex();
    }

    public JButton getBtnRegisterDonatur() {
        return btnRegisterDonatur;
    }

    public JButton getBtnRegisterPenggalangDana() {
        return RegisterPenggalangdanaBtn;
    }

    public JList getListuser() {
        return ListNama;
    }

    public JList getListPenggalang() {
        return ListPenggalang;
    }

    public JButton getBtnBacktologin() {
        return btnBacktologin;
    }

    public JButton getBtnViewPenggalangDana() {
        return btnViewPenggalangdana;
    }

    public JButton getBtnViewDonatur() {
        return btnViewDonatur;
    }

    public void setText(String s) {
        taInfo.setText(s);
    }
    
    public void setTextPenggalang(String s){
        Penggalangdana.setText(s);
    }

    public Date getjDateLahir() {
        return jDateLahir.getDate();
    }

    public void addActionListener(ActionListener e) {
        btnRegisterDonatur.addActionListener(e);
        RegisterPenggalangdanaBtn.addActionListener(e);
        btnBacktologin.addActionListener(e);
        btnViewPenggalangdana.addActionListener(e);
        btnViewDonatur.addActionListener(e);
    }

    public void addmouseadapter(MouseAdapter me) {
        ListNama.addMouseListener(me);
        ListPenggalang.addMouseListener(me);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListNama;
    private javax.swing.JList<String> ListPenggalang;
    private javax.swing.JTextArea Penggalangdana;
    private javax.swing.JButton RegisterPenggalangdanaBtn;
    private javax.swing.JTextField Tempat;
    private javax.swing.JButton btnBacktologin;
    private javax.swing.JButton btnRegisterDonatur;
    private javax.swing.JButton btnViewDonatur;
    private javax.swing.JButton btnViewPenggalangdana;
    private javax.swing.JComboBox<String> cbGender;
    private com.toedter.calendar.JDateChooser jDateLahir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea taInfo;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNohp;
    private javax.swing.JPasswordField tfPass;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
